name: extended_http
description: Extends HTTP package to provide cache, store user credential,
  predefined authorization workflow, set custom request headers,
  beautiful logs and easy debugging with request debugId
version: 1.3.12
homepage: https://github.com/ngoan98tv/extended_http

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  path_provider_platform_interface: ^2.0.6
  plugin_platform_interface: ^2.1.4

flutter:
